name: AWS S3 배포 및 CloudFront 캐시 무효화 자동화

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4 # npm과 같이 'Marketplace'라는 G.A 라이브러리

      - name: Github Repository 파일 출력하기
        run: ls # Repository의 원본 파일들의 목록 확인 (빌드파일x)

      - name: React 프로젝트의 의존성 파일 설치하기
        run: npm i

      - name: 빌드하기
        run: npm run build # Github Actions의 Ubuntu runner는 Node.js가 사전 설치됨

      - name: 빌드용 파일이 생성된 dist 폴더 확인하기
        run: |
          ls
          echo "------------------"
          cd dist
          ls

      - name: AWS Resource에 접근을 위한 인증 설정하기
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일들 전체 삭제하기
        run: aws s3 rm --recursive s3://facebook-web-kosmosticlay

      - name: S3에 빌드된 파일 업로드하기
        run: aws s3 cp ./dist s3://facebook-web-kosmosticlay/ --recursive
