name: AWS S3 배포 및 CloudFront 캐시 무효화 자동화

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4 # npm과 같이 'Marketplace'라는 G.A 라이브러리

      - name: Github Repository 파일 출력하기
        run: ls # Repository의 원본 파일들의 목록 확인 (빌드파일x)

      - name: React 프로젝트의 의존성 파일 설치하기
        run: npm i

      - name: 빌드하기
        run: npm run build # Github Actions의 Ubuntu runner는 Node.js가 사전 설치됨

      - name: 빌드용 파일이 생성된 dist 폴더 확인하기
        run: |
          ls
          echo "------------------"
          cd dist
          ls
